ALTER TABLE loading.akeneo ADD COLUMN product_hash character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN mfg_id integer;
ALTER TABLE loading.akeneo ADD COLUMN id integer NOT NULL DEFAULT nextval('product_id_seq'::regclass);
ALTER TABLE loading.akeneo ADD COLUMN atero_cat_id integer;
ALTER TABLE loading.akeneo ADD COLUMN variant_hash1 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash2 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash3 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash4 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash5 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash6 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash7 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash8 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash9 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN variant_hash10 character varying(50) COLLATE pg_catalog."default";
ALTER TABLE loading.akeneo ADD COLUMN post_msrp numeric(12,2);
ALTER TABLE loading.akeneo ADD COLUMN post_depth numeric(10,3);
ALTER TABLE loading.akeneo ADD COLUMN post_shipping_weight numeric(10,3);
ALTER TABLE loading.akeneo ADD COLUMN post_unit_of_measure character varying(50) COLLATE pg_catalog."default";
